name: publish nuget

on:
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          10.0.x

    - name: Install dotnet tool
      run: dotnet tool install -g dotnetCampus.TagToVersion

    - name: Set tag to version
      run: dotnet TagToVersion -t ${{ github.ref }}

    - name: Build with dotnet
      run: |
        dotnet build --configuration release
        dotnet pack --configuration release --no-build src\DotNetCampus.HttpClientOverOpenSsl\DotNetCampus.HttpClientOverOpenSsl.csproj

    - name: Push generated package to NuGet
      run: |
        dotnet nuget push .\artifacts\package\release\*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NugetKey }}
        dotnet nuget push .\artifacts\package\release\*.nupkg -s https://nuget.pkg.github.com/${{ github.repository_owner }} --api-key ${{ secrets.GITHUB_TOKEN }} --timeout 3000
